server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    open-in-view: true # osiv 설정, default = true
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true

  security:
    user:
      name: test
      password: 1234

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

